### ISSUE TITLE
A basic issue about analysis  SAMPLE DATA by mimseq 

### ISSUE THREAD

**Issue by Ashring-Tang** [nedialkova-lab/mim-tRNAseq#10]
Hi，
      Sorry to bother you，I just begin to study running mimseq and try to analysis the sample data you upload in the supplements. But I face on an error  ‘ mimseq: error: unrecognized arguments: --snp-tolerance --cca-analysis' 
 after type  "mimseq --species Hsap --cluster --cluster-id 0.95 --snp-tolerance --cca-analysis --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg19_test --out-dir hg19_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 sampleData_HEKvsK562.txt" .I am a green hand in bioinformatic analysis. Would you like to help me solve above issue， thanks for your help!

**Comment by drewjbeh** [comment]
Hi there,

This error is because in newer versions of mimseq I have removed some parameters and instead made these options enabled by default, for example SNP tolerant alignment and CCA anlaysis. Instead, now there are new parameters to disable these options if so desired, for example with `--no-snp-tolerance` and `--no-cca-analysis`, although I recommend leaving these options activated. The idea was to make the commands shorter and easier to build.  
I will update the documentation for mimseq and the example data to match the new version - thanks for bringing this up!

**Comment by drewjbeh** [comment]
You could/should also change `--species Hsap` to `--species Hsap38` to use the newer hg38 human genome and matching tRNA predictions. You can change the output directory and experiment name to match as well for record keeping (i.e. hg19 to hg39). The new example command can be seen on the github REAME
