### ISSUE TITLE
Questions about Spikein

### ISSUE THREAD

**Issue by AngLiRNA** [nedialkova-lab/mim-tRNAseq#28]
Hi,
Thanks for providing the amazing mimseq, I've successfully ran it and got very useful results.
I have 2 questions about the spinkin.
1, Will mimseq normalize the data by spikin for DESeq2 analysis? I read the paper and noticed when doing DESeq to calculate the tRNA abundance, it will normalize to library size but nor sure if it will normalize the difference of spikin. It seems the spikein is used for CCA analysis? I also found the presence of Ecoli-lys-TTT in the Deseq2 output file.
2, I acturally added 3 spikeins into the samples, and the reference only contain Ecoli-Lys-TTT, if I want add another 2 into the reference, what should I do, should I genernate the reference by myself?

Thank you so much,
Ang

**Comment by nedialkova-lab** [comment]
Hi Ang, it's great to hear that you've been getting useful results with mimseq. Regarding your questions: 

1) The data is not normalized to the E. coli tRNA-Lys-TTT spike-in prior to DESeq. If you would find normalization useful for a specific question, you can do this by starting with the raw counts table in the mimseq "counts" directory. In our view it is hard to interpret data normalized to the spike-in, since it's hard to distinguish biological from technical variations. We do include the E.coli tRNALys-TTT in the DESeq analysis because it may be a useful indicator of whether the amount of tRNA as a fraction of total RNA changes in different conditions. This may mean that there are fewer or more tRNAs per ribosome in a specific condition,  but to confirm this the abundance of e.g. ribosome subunits would have to be carefully quantified as well.  Plotting the spike-in in the CCA analysis is useful because we always add CCA vs CC-containing E. coli tRNA-Lys-TTT i a 3:1 ratio. By looking how closely this ratio is recapitulated after sequencing, we can rule out biases towards one or the other type of tRNA 3' ends. 

2) Yes - there is some information on how to go about doing this in the "Input Files" section here https://mim-trnaseq.readthedocs.io/. Alternatively, if the other spike-ins come from one of the organisms included in mimseq, you could take the unaligned reads from your first run and do a second round of mimseq alignment to get the spike-in counts.

I hope this helps,
Danny
