### ISSUE TITLE
GMAP version 2017-11-15

### ISSUE THREAD

**Issue by Futa0908** [nedialkova-lab/mim-tRNAseq#67]
Hi, there.
When installing mimseq using conda-forge according to the protocol, the version of GSNAP-GMAP becomes 2017-11-15 instead of 2019-02-26 and mimseq does not work properly. What should I do in such a case? Is it?

**Comment by nedialkova-lab** [comment]
I suggest deleting the environment and repeating the installation process - the GSNAP version that came with mimseq1.3.8 installed with mamba was 2019-02-26 for me.

**Comment by drewjbeh** [comment]
Hi there,

One issue with conda is that it is known to have problems with reproducibility (see [this](https://github.com/conda/conda/issues/2997) for example). That is, the environments can look different on different machines. The issue might be your conda version. I am using conda 23.3.1 installed with the miniforge installer. Unfortunately, for whatever reason, your environment ends up with the wrong GMAP version. If repeating the environment installation as suggested, or perhaps installing conda with the same version as me does not help, I would suggest manually upgrading GMAP/GSNAP using mamba in your environment. This should be painless and quick, and will hopeful work. 
Unfortunately, due to conda's complicated depenency handling, I cannot change anything in the conda package without breaking things. Hope this helps.

**Comment by vcognat** [comment]
Hi,
I had the same issue and upgrading didn't work. To solve the problem I installed GSNAP 2019-02-26 in my conda env before installing mimseq.
Hope this can help someone ...

**Comment by nedialkova-lab** [comment]
Great thanks for that!
