### ISSUE TITLE
Interpretation of the "proportion" Column in mismatchTable.csv

### ISSUE THREAD

**Issue by Xinkai-Wu** [nedialkova-lab/mim-tRNAseq#73]
Hello. I am a bit confused while interpreting the output file from mim-tRNASeq. The mismatchTable.csv lists the proportions of four types of bases at each position. However, why is the sum of the proportions for the four bases not equal to 1? Thanks!

Below is an example from the test data.

isodecoder      canon_pos       pos     type    proportion      cov     condition       bam
Homo_sapiens_mito_tRNA-Ala-TGC-1        1       1       A       0.0     534.0   HEK293T hg38_HEK239vsK562/mimseq_hek_1.unpaired_uniq.bam
Homo_sapiens_mito_tRNA-Ala-TGC-1        1       1       C       0.0     534.0   HEK293T hg38_HEK239vsK562/mimseq_hek_1.unpaired_uniq.bam
Homo_sapiens_mito_tRNA-Ala-TGC-1        1       1       G       0.0     534.0   HEK293T hg38_HEK239vsK562/mimseq_hek_1.unpaired_uniq.bam
Homo_sapiens_mito_tRNA-Ala-TGC-1        1       1       T       0.0     534.0   HEK293T hg38_HEK239vsK562/mimseq_hek_1.unpaired_uniq.bam

Best,
Xinkai

**Comment by drewjbeh** [comment]
Hi there. The mismatch table gives the proportion of misincorporation of
each base at each position. The sum gives the total misincorporation at
that position, not the total proportion of each base. There should be a NA
value for each position and this refers to the reference nucleotide at this
position. This is NA because you cannot count a misincorporation of the
same base that was already there.
For more info on output files please see
https://mim-trnaseq.readthedocs.io/en/latest/output.html

**Comment by Xinkai-Wu** [comment]
Hi Drew, thank you for your response.
