### ISSUE TITLE
figure of anticodon_vst_hp.png

### ISSUE THREAD

**Issue by YueZhang2019** [nedialkova-lab/mim-tRNAseq#8]
Hi 

onuryukselen helped us to run mim-tRNAseq with our custom mouse data on the dolphinnext platform.  After fixing the #7 ,I got my results from the pipeline.  They are wonderful.  Thank you for your help.

Here I have some questions:

1. In the first try of pipeline, I got a figure named “anticodon_vst_hp.png” (only 4 samples that not touch off the bug), but it didn't show up by the updated version.  Did you remove this function?  Is it replaced by “ED_isodecodersScaled_hp.pdf”？
![image](https://user-images.githubusercontent.com/10041578/117198819-78aa9e00-adb7-11eb-884a-5611b4c569f6.png)

2. If not, which output file should I use to plot a similar figure?
3. In the ED_isodecodersScaled_hp.pdf, is each row for one isodecoder?  Which one is the output file so that I can plot the name of each row?

Thank you so much.

Yue

**Comment by drewjbeh** [comment]
Hi there,

Glad to have helped you get some good results using mim-tRNAseq. Here are some answers to your questions:

1. Indeed we removed the vst heatmaps as they weren't that informative. These are replaced by the `DE_anticodonScaled_hm.pdf` and `DE_isodecoderScaled_hm.pdf` graphs in the `DESeq2/anticodon` and `DESeq2/isodecoder` folders, respectively. The difference between these is that the new ones use scaled normalised counts instead of variance stabilizing transformed (vst) counts, there is also log2 fold change values for each condition vs the control condition, and we filter to only show genes (anticodons or isodecoders) that are differentially expressed instead of all genes as in the vest plots. This is because most genes are not differentially expressed and so have very similar colours on the heatmaps and are not very informative about condition-specific expression of tRNAs.
2. If you still would like to plot the old version, there is a file called `vst-transformedCounts.csv` in both the DESeq2 anticodon and isodecoder folders you could use. You could also use `counts/Anticodon_counts_DESEqNormalized.csv` and `counts/Isodecoder_counts_DESEqNormalized.csv` for normalised DESeq2 counts, and apply scaling in R (`scale()`) to recreate the values used in the new plots.
3. We left out the row names for the isodecoder plot as there are usually too many to list properly. The text becomes unreadable as the names overlap. For anticodons there are few enough to list individually. However, as I said in 1. we filter the results in these heatmaps for significantly differentially expressed genes only. This means you can use the DESeq2 results files to see which isodecoders are differentially expressed in which conditions. In your case the file will be something like `DESeq2/isodecoder/ExprvsCtrl_diffexpr-results.csv`. In here you will find the adjusted p-value (we filter for p-adj <= 0.01), the fold change which is also plotted in the new plots, as well as the normalised counts for every sample in the last columns.

For more details about outputs, please see the mim-tRNAseq documentation (https://mim-trnaseq.readthedocs.io/en/latest/output.html).

By the way, I noticed that there is quite some difference between the two Ctrl replicates in the image you posted above. You might want to look at the `qc-pca.png` PCA plots and `qc-sampledists.png`, especially for isodecoders to see how your samples cluster, and the replicability between them. This really effects the differential expression analysis.

**Comment by YueZhang2019** [comment]
Hi,

Sorry to bother you.  But I found more concerns.

4  In my project, we gave suppressor tRNA to Expr group mice, but not to the Ctrl group.  But I found there are lots of counts 
 of suppressor tRNA  in ctrls? 
![image](https://user-images.githubusercontent.com/10041578/117201283-7c8bef80-adba-11eb-9c97-74dc28f250c5.png)
5. Should I change the mismatch stringency of this pipeline? Maybe concern2 is due to mismatch. Should I set –max-mismatches 0?  How is about –remap-mismatches?

Thank you

**Comment by drewjbeh** [comment]
Hi there,

The first thing I would check is the sequence of the SupCTA sequence you gave to the mice compared to all other mouse tRNAs. If its is similar to some other sequences then it would be difficult to discriminate reads mapping to it vs some other mouse tRNA, especially since there is no modification information for this tRNA.

You could try lowering the mismatch threshold for sure - that's a good start. I would try avoid setting it to 0 as this might prevent reads with unknown modifications mapping correctly. mim-tRNAseq uses Modomics data initially, and of course like any DB this data is not complete. So any unknown modifications might be missed. Adjusting remap mismatches is also a good place to start, perhaps even better than --max-mismatches, as a lot of new modifications would already have been detected by this point.

The other thing I can suggest is to actually have a look at the data in IGV for example. You can use the `/annotation/*clusterTranscripts.fa` file as a genome reference, and the bam files of uniquely mapped reads in `align/*unpaired_uniq.bam`. Be sure to index these bam files first to enable you to load them into IGV. From here you can view your suppressor tRNA and the reads mapping to it in a Ctrl and a Expr sample. Assess the mismatches in the reads and this might help identify whether --max-mismatches or --remap-mismatches is leading to mismapping.

**Comment by YueZhang2019** [comment]
Hi

Our suppressor tRNA differs from the endogenous mouse tRNA-Tyr by only one nucleotide.

I am working on IGV for Ctrl and Expr samples (you have the Ctrl3 and Expr3 samples from issue #7  ).

![image](https://user-images.githubusercontent.com/10041578/117348732-8b38dc00-ae78-11eb-9479-5e4f1135d42a.png)
I have loaded Ctrl1 and Expr1 to IGV, the red frame highlighted the engineered anticodon to readthrough UAG stop codon.
Sorry, I don’t know much about bioinformatic analysis. 

How could I identify whether --max-mismatches or --remap-mismatches is leading to mismapping? 

Here is my setting: --cluster --cluster-id 0.95  --threads 10 --min-cov 2000 --max-mismatches 0.1 --max-multi 1 --remap --remap-mismatches 0.075

Thank you for your help.

**Comment by drewjbeh** [comment]
Hi

There are a few possible issues here that could be the problem. Firstly, you can see a drastic reduction in coverage of reads before the anticodon, probably due to that modification at position 37 which you can see by the mismatch profile at that nucleotide. This means you have very few reads actually covering the anticodon where the only distinguishing nucleotide between your Sup and the mouse Tyr tRNA is. One nucleotide difference is already very small and might be difficult for mim-tRNAseq to distinguish, but since there are very few reads covering the anticodon this information is not present and reads up to this point are identical for Sup and Tyr. Perhaps you can optimise the RT reaction more to enable better read-through of this position 37 modification? I know that in humans, Tyr-GTA has a double m2,2G modification at position 26 and 27 that we have a tough time reading through, and if present in mouse this might be a problem for you too, but if you can at least get through the anticodon that will help with read assignment.

Secondly, there seems to be at least 4 modified sites in your sequencing reads upstream of the anticodon (as seen by the mismatch profiles from your IGV screenshot). I don't know the details about your experiment, and whether the Sup tRNA you are using is synthesised or not, and whether it is endogenously modified or you expect no modifications? If you don't expect it to be modified, then this is clearly misalignment probably from the Tyr tRNA which would be modified. Perhaps you could check `mods/predictedMods.csv` to see if mim-tRNAseq is predicting new mods for the Sup tRNA after the first round of alignment. If so, and you don't expect this tRNA to be modified, then perhaps you could try reducing `--max-mismatches` and don't perform remapping (so remove `--remap` and `--remap-mismatches` from your command). This might help the misalignment and you would be able to tell by reassessing the alignments in IGV as you have done, and checking the profile of the reads that are aligning to the Sup tRNA.

The most ideal solution would be to use a sequence that differs by more nucleotides than just 1 from other mouse tRNAs, but again I don't know the details of your experiment and if this is possible or not.
